# Generated by Django 3.2.18 on 2023-03-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230304_1202'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('product', 'customer'), name='unique product and customer'),
        ),
    ]
