# Generated by Django 3.2.18 on 2023-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_unique product and customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='full_title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
